using System;
using SQLite;
using static PerkyTemp.Utilities.Utilities;

namespace PerkyTemp.Models
{
    /// <summary>
    /// A model representing a past session.
    /// This is stored in the database using PerkyTempDatabase.
    /// </summary>
    /// <seealso cref="PerkyTempDatabase"/>
    public class PastSession
    {
        /// <summary>
        /// The ID of the session. This is automatically generated by SQLite.
        /// </summary>
        [PrimaryKey, AutoIncrement]
        public int ID { get; private set; }

        /// <summary>
        /// The start timestamp of the session, as a Unix timestamp.
        /// </summary>
        public double StartDateTimestamp { get; private set; }

        /// <summary>
        /// The end timestamp of the session, as a Unix timestamp.
        /// </summary>
        public double FinalDateTimestamp { get; private set; }

        /// <summary>
        /// The first temperature of the session, in degrees celsius.
        /// </summary>
        public float StartTemp { get; private set; }

        /// <summary>
        /// The last temperature in the session, in degrees celsius.
        /// </summary>
        public float FinalTemp { get; private set; }

        /// <summary>
        /// A string representation of the date that the session started.
        /// </summary>
        [Ignore]
        public string Date
        {
            get
            {
                return UnixTimestampToDateTime(StartDateTimestamp).ToString();
            }
        }

        /// <summary>
        /// A string representation of the duration of the session.
        /// </summary>
        [Ignore]
        public string DurationString
        {
            get
            {
                return Math.Round(TimeSpan.FromSeconds(FinalDateTimestamp - StartDateTimestamp).TotalMinutes) + " minutes";
            }
        }

        /// <summary>
        /// Empty constructor - required for SQLite.
        /// </summary>
        public PastSession() { }

        /// <summary>
        /// Create a new PastSession from the required fields.
        /// </summary>
        public static PastSession FromFields(DateTime StartDateTime, DateTime FinalDateTime, float StartTemp, float FinalTemp) {
            PastSession session = new PastSession();
            session.ID = 0;
            session.StartDateTimestamp = DateTimeToUnixTimestamp(StartDateTime);
            session.FinalDateTimestamp = DateTimeToUnixTimestamp(FinalDateTime);
            session.StartTemp = StartTemp;
            session.FinalTemp = FinalTemp;
            return session;
        }

        /// <summary>
        /// Convert this PastSession to a string (for debugging purposes).
        /// </summary>
        public override string ToString()
        {
            return string.Format("[PastSession: ID={0}, StartDateTime={1}, FinalDateTime={2}, StartTemp={3}, FinalTemp={4}]",
                ID,
                UnixTimestampToDateTime(StartDateTimestamp),
                UnixTimestampToDateTime(FinalDateTimestamp),
                StartTemp,
                FinalTemp);
        }
    }
}
